baseurl = "https://amcloudsolutions.de"
metaDataFormat = "yaml"
title = "AM Cloud Solutions"
theme = "blist"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Hey! I'm Antonius"
      introSubtitle = "29 y/o DevOps engineer and passionate software developer. My principles: Stay on top of the game, share your knowledge and work on your customer's future as if it were yours."
      searchBar = "Search"
      searchBarPlaceholder = "Enter search query"
      searchBarResults = "Results"
      searchBarNoResults1 = "No results found"
      searchBarNoResults2 = "Try adjusting your search query"
    [languages.en.params.homepage.social]
        title = "Follow me"
        description = "I share my work in the blog section of this homepage you can find all the code on my public github."
    # [[languages.en.menu.main]]
    #     name = "Blog"
    #     url = "blog"
    #     weight = 1
    [[languages.en.menu.main]]
        name = "CV"
        url = "cv"
        weight = 2
    [[languages.en.menu.main]]
        name = "Contact"
        url = "contact"
        weight = 3
    [[languages.en.menu.main]]
        name = "Impress"
        url = "impress"
        weight = 4

  [languages.de]
    contentDir = "content/de" # Deutsch
    weight = 2
    languageName = "Deutsch"
    title = "AM Cloud Solutions"
    [languages.de.params]
      introTitle = "Hallo! Ich bin Antonius"
      introSubtitle = "29-jähriger DevOps Engineer und Software-Entwickler aus Leidenschaft. Meine Prinzipien: Bleib am Puls der Zeit, teile dein Wissen und arbeite für die Zukunft der Kunden, als wäre es deine eigene."
      searchBar = "Suche"
      searchBarPlaceholder = "Sucheingabe"
      searchBarResults = "Ergebnisse"
      searchBarNoResults1 = "Keine Ergebnisse gefunden"
      searchBarNoResults2 = "Versuche die Suche anzupassen"
    [languages.de.params.homepage.social]
        title = "Folgt mir"
        description = "Ich präsentiere meine Arbeit in Form der Blogbeiträge auf dieser Seite, ihr findet den Code auf meinem öffentlichen github Account." 
    # [[languages.de.menu.main]]
    #     name = "Blog"
    #     url = "blog"
    #     weight = 1
    [[languages.de.menu.main]]
        name = "Lebenslauf"
        url = "cv"
        weight = 2
    [[languages.de.menu.main]]
        name = "Kontakt"
        url = "contact"
        weight = 3
    [[languages.de.menu.main]]
        name = "Impressum"
        url = "impress"
        weight = 4
        
#   [languages.dy]
#     contentDir = "content/dy" #Example language
#     weight = 3
#     languageName = "Test Language"

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = false
  defaultThemeDark = true
  logo = "/logo-no-background.svg"
  introPhoto = "/profilePic.jpg"
  cvPhoto = "/cv-pic.jpg"

  name = "Antonius Malsam"
  email = "antonius.malsam@amcloudsolutions.de"
  phone = "+49 176 81669291"
  # Enable search in header
  enableSearch = false

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
  ]

  # Custom copyright - optional
#   copyright = "Copyright © 2021 - Katheryn Fox · All rights reserved"
  favicon = "/logo-color.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = true

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = false

# Comments system
[params.comments]
  # Supports disqus, giscus and utterances
  # Check hugo docs for setting up disqus
  system = "giscus"

  # Options for giscus, exclude hyphens
  repo = ""
  repoid = ""
  category = ""
  categoryid = ""
  mapping = ""
  strict = ""
  reactionsenabled = ""
  emitmetadata = ""
  inputposition = ""
  theme = ""

  # Options for utterances, exclude hyphens
  # repo = ""
  # issueterm = ""
  # theme = ""

[params.homepage.social]
  # Global params common for both languages
  title = "Follow me"
  description = "I shary my work in the blog section of this homepage you can find all the code on my public github."

  [[params.homepage.social.icons]]
    website = "linkedin"
    url = "https://www.linkedin.com/in/antonius-malsam/"
  [[params.homepage.social.icons]]
    website = "github"
    url = "https://github.com/AntoniusMa"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true

[module]
  [[module.imports]]
    path = "github.com/schnerring/hugo-mod-json-resume"
  [[module.mounts]]
    source = "node_modules/simple-icons/icons"
    target = "assets/simple-icons"